kind: ConfigMap
apiVersion: v1
metadata:
  name: text-sentiment-ml-backend-config
  labels:
    dependency.staroid.com/export: labelstudio-ml-backend-config
data:
  ML_BACKEND_URL: "http://text-sentiment.{{.Namespace}}:9090"
