# Staroid uses skaffold to build container images and deploy Kubernetes manifests.
apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: text-sentiment
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - text-sentiment-k8s.yaml
      - model-config-k8s.yaml
profiles:
  - name: minikube
    patches:
      - op: add
        path: /deploy/kubectl/manifests/0
        value: minikube.yaml
